### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by xereda** [Wanderxx/vue-fullcalendar#10]
The version I tested installing your component is different from the one you see in the gif below:

https://camo.githubusercontent.com/54f8793a0c6b4b226752414a7067b0a9c2850951/687474703a2f2f672e7265636f726469742e636f2f766f7674654a356d396f2e676966

What I need to have available, for example, the context menu and the top left button.

Thanks for the feedback.

**Comment by xereda** [comment]
![calendar](https://cloud.githubusercontent.com/assets/14337850/20686834/4fbab452-b5a1-11e6-8e6d-924592607758.gif)

**Comment by Wanderxx** [comment]
Hi,

The event Card and context Menu is written based on others' business logic. So it's not inside the fullcalendar.

However, you'll still be able to register your own event Card & context Menu to the fullcalendar
by using slot `fc-header-right` and `fc-body-card`

**Comment by silvestreh** [comment]
Got any quick documentation on slot usage? I've been going through the source but I was unable to figure it out.

For example, I'd like to display:

| prev/next button | month/year | today button  |
| --------------------- |:---------------:| ------------------:|

And for the date I'd like to use `December, 2016` format. 

Is this possible?
