### ISSUE TITLE
Event background color?

### ISSUE THREAD

**Issue by ghost** [Wanderxx/vue-fullcalendar#14]
Fullcalendar has a huge list of available object properties for events, and it seems many of which are not supported in vue-fullcalendar? These should just be passed through but it seems they are not.

For example, I am currently assigning a "backgroundColor" property to each of my events from my server and fetching in Vue, but this property does not seem to translate to the fullcalendar instance.

Documentation is not clear here on how I would achieve this. I can hack it in, but would rather avoid that.

**Comment by Wanderxx** [comment]
Hi there,

1. This project is inspired by fullCalendar.js but not cloned by it. 
2. Your idea can be done by set different `cssClass` in each `event` Object you have.

**Comment by Wanderxx** [comment]
#6 See here also

**Comment by ghost** [comment]
@Wanderxx OK I understand, but I would still then suggest the following.

1. Rename vue-fullcalendar to avoid confusion. At the very least please mention in the docs that it does not use the same library and fullcalendar.js options are not supported.
2. Consider adding more features from fullcalendar such as this color. I understand I can mimic the effect with css Class, but in my instance I have a server with event categories where users can choose the color for their category dynamically. I do not want to have to maintain a separate stylesheet if I don't have to here.

For now I will roll my own customization into your calendar plugin.

**Comment by Wanderxx** [comment]
Hi there,

I guess renaming proj is the last thing I wanna do, but providing some mentions is optional.
And, things like fontSize textColor backGroundColor ,etc. could all be handled by a single `cssClass`.
Also, this proj is 100% open source, you could just do whatever you want with the piece of code.
Suite yourself well. ^_^
