### ISSUE TITLE
Error when including in project

### ISSUE THREAD

**Issue by Alex-Sokolov** [Wanderxx/vue-fullcalendar#15]
```
[Vue warn]: Error when rendering component <full-calendar> at /Users/SunnyWang/code/vue-fullcalendar/src/fullCalendar.vue: 
```

Found that in `vue-calendar.js` there are some place with wrong path:
```
__vue_options__.__file = "/Users/SunnyWang/code/vue-fullcalendar/src/components/header.vue"
```

Using vue.js 2.1.6

Looks like need to be recompiled with latest version:
https://github.com/vuejs/vue/commit/4b51ad048306367a6fb6fbee7445e086d855f31e

**Comment by Alex-Sokolov** [comment]
Temporary changed from `dist` to `src`.

P.S: Can you change requiring vue-files with extensions too? Because it's not obviously to add `vue` extenstion to resolve option of webpack.

**Comment by Wanderxx** [comment]
Hey,

Thanks for mention, just updated to make it work with latest `Vue`. You can check out from  npm now.

And for your second issue, I am strongly recommend you adding `vue` extension in a `vue-webpack` project, which will just make your life better.

**Comment by Alex-Sokolov** [comment]
Thanks!

**Comment by Alex-Sokolov** [comment]
But not building with new version
Error in vue-calendar.js
```
ReferenceError: _h is not defined

module.exports={render:function (){with(this) {
	  return _h('div', {
	    staticClass: "comp-full-calendar"
	  }, [_h('fc-header', {
	    attrs: {
	      "current-date": currentDate,
	      "title-format": titleFormat,
	      "first-day": firstDay
	    },
```

**Comment by Wanderxx** [comment]
Sure you're using the latest `vue-fullcalendar@1.0.5` ?

**Comment by Alex-Sokolov** [comment]
Oh. Sorry, my bad :D update package.json but forgot to `npm i`
