### ISSUE TITLE
title-format options

### ISSUE THREAD

**Issue by ghost** [Wanderxx/vue-fullcalendar#16]
Hi, can't parse title-format in English to get the Month displaying as TEXT instead of Numbers. What formatting am I expect to send to the title-format prop?

**Comment by Wanderxx** [comment]
Hi,

right now, fullMonthName is set to be default. And you can also set `titleFormat` as `MMMM yyyy` to get `December 2016`, or `MMM yyyy` to `Dec 2016` and `MM yyyy` to `12 2016`

**Comment by Wanderxx** [comment]
Don't to forget to check out latest version

**Comment by ghost** [comment]
thank you. working now. I did try that but turns out I didn't have the latest version. Thanks!
