### ISSUE TITLE
Week view

### ISSUE THREAD

**Issue by ammadtarar** [Wanderxx/vue-fullcalendar#21]
am using vue-calendar . it works fine for month view . Is there a way to show week view using this calendar ? or can you recommend any other calendar that have week view ?

**Comment by Wanderxx** [comment]
Hi,

I have to say this calendar only supports month view right now. ^_^

**Comment by askz** [comment]
Hi, is it hard to get if I get my hands in?

**Comment by jsinhSolanki** [comment]
Are you palanning to implement week view or day view??
