### ISSUE TITLE
Unable to set shortMonth via locale

### ISSUE THREAD

**Issue by Alex-Sokolov** [Wanderxx/vue-fullcalendar#22]
Inside dateFunc.js there are `shortMonth` and `defMounthNames`
Later `format` function use monthNames from parameter and default if not included
```js
 format (date, format, monthNames) {
    monthNames = monthNames || defMonthNames
```
but for `shortMonth` there is no alternative

**Comment by Wanderxx** [comment]
Yes, I will add this later
