### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by SergeyMiracle** [Wanderxx/vue-fullcalendar#55]
How to change locale?
I've been trying - fr, zh, ru but all in vein... Locale always stays default - 'en'

```
<full-calendar :events="events"
                     locale="ru"
                     firstDay="1"
                     @eventClick="eventClick">
      </full-calendar>
```

**Comment by freedom-zt** [comment]
lang="en"

**Comment by freedom-zt** [comment]
lang="ru"

**Comment by SergeyMiracle** [comment]
@freedom-zt in docs: `locale : langague of things like monthNames weekNames and titleFormat. Support same locales than moment.js`
lang option i guess not moment.js locales

**Comment by SergeyMiracle** [comment]
Ok now i see, locale param only works in master branch

**Comment by jemliF** [comment]
I set the locale to 'fr' but still getting month and day names in english

`<full-calendar :events="events" locale="fr"></full-calendar>` 

What's the problem?

**Comment by SergeyMiracle** [comment]
@jemliF locale param only works in master branch

**Comment by jemliF** [comment]
@SergeyMiracle What do you mean? I followed installation and usage steps, how to fix this?

**Comment by SergeyMiracle** [comment]
@jemliF wait till next release i guess

**Comment by jemliF** [comment]
@SergeyMiracle I have a look to the source code, it's already there, but don't know why it's not working !

**Comment by SergeyMiracle** [comment]
@jemliF It's in the source code in master branch, and if u use command `npm install vue-fullcalendar@latest --save ` to install pkg, it gives u no MASTER branch but latest release - 1.0.9 where `locale` do not exists!
What i did - just copied this project from master branch and made it work, now i how my custom component, based on this project. You should do the same, coz this pkg kind of broken (i mean master branch)
