### ISSUE TITLE
Start of the week

### ISSUE THREAD

**Issue by mihaliak** [Wanderxx/vue-fullcalendar#7]
How to set start of the week to monday ? Currently table columns are in this order:
Sun Mon Tue Wed Thu Fri Sat

Is there any way how to move Sunday to last position so week will start with Monday?

Thanks for help

**Comment by mihaliak** [comment]
If someone will need it I had to make custom build for it just change https://github.com/Wanderxx/vue-fullcalendar/blob/master/src/components/body.vue#L143

to 
`startDate.setDate(startDate.getDate() - curWeekDay + 1)`

1 will add one day to start of the week so if you change it to 2 week will start on Tuesday.

Also dont forget to change langSet array of weekNames.

**Comment by Wanderxx** [comment]
Hi mihaliak,

Apologize for late respond, I was on a long vacation. I just added another prop `firstDay`, which let you set start of the week.
It should be `Number`, takes from 0 (Sunday) to 6 (Saturday).
Go, check out!
