### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by GrofGraf** [Wanderxx/vue-fullcalendar#9]
If i try to import fullCalendar in my .vue file, server starts normally, but when I navigate to localhost I get the following error:

> Error: window is not defined
> ReferenceError: window is not defined
>     at __vue_ssr_bundle__:6236:32
>     at __vue_ssr_bundle__:6231:49
>     at module.exports (__vue_ssr_bundle__:6253:70)
>     at Object. (__vue_ssr_bundle__:6133:38)
>     at __webpack_require__ (__vue_ssr_bundle__:6037:31)
>     at Object. (__vue_ssr_bundle__:6084:3)
>     at __webpack_require__ (__vue_ssr_bundle__:6037:31)
>     at Object.__vue_styles__ (__vue_ssr_bundle__:6066:23)
>     at __webpack_require__ (__vue_ssr_bundle__:6037:31)
>     at __vue_ssr_bundle__:6057:19

Do you have any idea, what am I doing wrong? Some guidance would be much appreciated. I am just starting with vue and have some problems figuring out SSR. Did some basic examples, now I am trying these in practice.

**Comment by Wanderxx** [comment]
Hi Grof,

First, a jsfiddle would always be much helpful.
Secondly It seems something was going wrong with SSR and I haven't test this project on server side yet. So, if you just want to figure out how fullcalendar works, you can directly download the whole project and type `npm run dev` to see the demo

**Comment by GrofGraf** [comment]
Thank you very much for your tip. Will try to play a bit with your code.

**Comment by lmj0011** [comment]
@GrofGraf 
any updates on this?

**Comment by lmj0011** [comment]
for anyone else who's stuck on this. see this solution:
https://github.com/nuxt/nuxt.js/issues/30#issuecomment-264348589

**Comment by yun-cn** [comment]
Vue-FullCalendar
app/plugins/vue-fullcalendar.js


import Vue from 'vue'
```
if (process.BROWSER_BUILD) {
  window.onNuxtReady(() => {
    const VueFullCalendar = require('vue-fullcalendar')
    Vue.use(VueFullCalendar)
  })
}
```
